### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by severak** [protomaps/protomaps-themes#9]
it seems that `https://protomaps.github.io/protomaps-themes/base/dist/index.js` is missing (and other errors cascade from that)

**Comment by bdon** [comment]
Thanks, this is broken right now on the Github Page but should work if you're running from a local checkout. It's a bit broken since I was previously publishing versions of this package to NPM, but I'm instead going to add a local build system that commits the build into GitHub pages - I haven't gotten around to this yet.

**Comment by severak** [comment]
it works from local checkout

**Comment by bdon** [comment]
https://protomaps.github.io/protomaps-themes now uses Vite+GH pages, so the demo should reflect what you get from local checkout in `app/` exactly.
